# Generated by Django 4.1.2 on 2022-10-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OEE', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
